[tools]
node = "25.2.1"
pnpm = "10.27.0"

[tasks.build]
description = "Build all packages"
depends = ["*:build"]

[tasks.test]
description = "Run all unit tests"
depends = ["*:test"]

[tasks."test:e2e"]
description = "Run all end-to-end tests"
depends = ["*:test:e2e"]

[tasks.check]
description = "Run all checks including build"
depends = ["build", "test", "test:e2e", "lint", "format"]

[env]
# default environment variables for development
S3_ACCESS_KEY_ID = "minio"
S3_SECRET_ACCESS_KEY = "miniominio"
S3_REGION = "minio"
S3_ENDPOINT = "http://localhost:9000"
S3_FORCE_PATH_STYLE = true
JWT_SECRET = "cca13c34b450a77c1d4b9ecd25dff6aebc6d7417afdb31864f5943c59abd03a1"
